import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import NavigationBar from "@/components/navigation";
import { headers } from "next/headers";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "에어비앤비 | 휴가지 숙소, 통나무집, 해변가 주택 등",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.ico",
  },
};

export default async function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  // TODO : Server-side 에서 pathname 알수있는 함수로, 중앙로직화
  const headersList = headers();
  // read the custom x-url header
  const domain = headersList.get("host") || "";
  const fullUrl = headersList.get("referer") || "";
  const pathname = fullUrl.substring(
    fullUrl.search(domain) + domain.length,
    fullUrl.length
  );
  console.log(" * fullUrl minus domain = pathname : ", pathname);
  const ismain =
    pathname === "/"; /* FIXME: / 이후 ? 파라미터 들어가는 경우도 커버할 것 */
  return (
    <html lang="en">
      <body className={inter.className} style={{ backgroundColor: "white" }}>
        <NavigationBar main={ismain} />
        {children}
      </body>
    </html>
  );
}
