enum ResponseMessage {
  SUCCESS = 'SUCCESS',

  VALIDATION_FAIL = 'VALIDATION FAIL',
  DUPLICATE_EMAIL = 'DUPLICATE EMAIL',
  SIGN_IN_FAIL = 'SIGN IN FAIL',
  EMAILAUTHCODE_FAIL = 'EMAIL AUTH CODE FAIL',

  MAIL_FAIL = 'MAIL FAIL',
  DATABASE_ERROR = 'BE ERROR',
}

export default ResponseMessage
